---
- name: Set up erlang and elixir
  hosts: localhost
  become_user: "{{ username }}"
  tasks:
    - name: install erlang, elixir, and rebar
      become: True
      become_user: root
      package: name={{ item }}
      with_items:
        - elixir
        - erlang
        - inotify-tools
        - rebar

  #   This is causing problems due to some esoteric DNS issue
    - name: install/update hex
      command: mix local.hex --force

    - name: install/update phoenix
      command: mix archive.install \
        https://github.com/phoenixframework/archives/raw/master/phx_new.ez
