---
- name: Set up erlang and elixir
  hosts: localhost
  become_user: "{{ username }}"
  tasks:
    - name: add erlang solutions key
      become: True
      become_user: root
      apt_key:
        url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
        state: present

    - name: add erlang solutions repo
      become: True
      become_user: root
      apt_repository:
        repo: deb https://packages.erlang-solutions.com/debian stretch contrib
        state: present
        update_cache: yes

    - name: install erlang, elixir, and rebar
      become: True
      become_user: root
      package: name={{ item }}
      update_cache: yes
      upgrade: dist
      with_items:
        - elixir
        - erlang
        - inotify-tools
        - rebar

  #   This is causing problems due to some esoteric DNS issue
    - name: install/update hex
      command: mix local.hex --force

    - name: install/update phoenix
      command: mix archive.install \
        https://github.com/phoenixframework/archives/raw/master/phx_new.ez
