---
- name: Set up erlang and elixir
  hosts: localhost
  become_user: "{{ username }}"
  tasks:
    - name: add erlang solutions key
      become: True
      become_user: root
      apt_key:
        url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
        state: present

    - name: add erlang solutions repo
      become: True
      become_user: root
      apt_repository:
        repo: deb https://packages.erlang-solutions.com/debian stretch contrib
        state: present
        update_cache: yes

    - name: dist upgrade
      become: True
      become_user: root
      apt:
        upgrade: dist

    - name: install erlang, elixir, and rebar
      become: True
      become_user: root
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - elixir
          - erlang
          - inotify-tools
          - rebar

  #   This is causing problems due to some esoteric DNS issue
    - name: install/update hex
      command: mix local.hex --force

    - name: install phoenix
      command: mix archive.install hex phx_new 1.4.0
