---
- name: Install development packages
  hosts: localhost
  become: yes
  # become_user: root
  # become_user: "{{ username }}"
  tasks:
    - name: Add repo ppa
      apt_repository:
        repo: 'ppa:numix/ppa'
        repo: 'ppa:phoerious/keepassxc'

    - name: install development packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
            - ack
            - build-essential
            - bzip2
            - curl
            - git
            - htop
            - tree
            - xclip
            - openssh-client
            - openssh-server
            # - libgoo-canvas-perl
            # - shutter
            - telegram-desktop
            - keepassxc
            - vlc
            - gnome-tweak-tool
            - numix-gtk-theme
            # - numix-icon-theme-circle
            - pipenv
    - name: Run bash script to compete the previous install
      script: ../cmd_install
