---
- name: Set Up Docker
  hosts: localhost
  become: True
  tasks:
    - name: install dnf-plugins-core
      package: name=dnf-plugins-core
               state=present

    - name: set up docker repo
      yum_repository:
        baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
        description: Docker CE Stable Repo
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/fedora/gpg
        name: "Docker CE Stable - $basearch"

    - name: upgrade all packages
      package:
        name: "*"
        state: latest

    - name: install docker-ce
      package: name=docker-ce
               state=present

    - name: ensure the docker group exists
      group: name=docker
             state=present

    - name: add user to docker group
      user: name={{ username }}
            groups=docker
            append=yes

    - name: enable docker service
      service: name=docker
               enabled=yes
               state=started
