---
- name: Run all the local playbooks
  hosts: localhost

- import_playbook: packages.yml
- import_playbook: docker.yml
- import_playbook: vim.yml
- import_playbook: zsh.yml
- import_playbook: node.yml
- import_playbook: watchman.yml
- import_playbook: vscode.yml
