---
- name: Install PostgreSQL and Extras
  hosts: localhost
  become: True
  become_user: root
  tasks:
    - name: install postgresql packages
      package: name={{ item }}
      with_items:
        - pgadmin3
        - postgresql
        - postgresql-contrib

    - name: ensure database exists
      command: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/base

    - name: enable postgresql service
      service: name=postgresql
               enabled=yes
               state=started
