---
- name: Set Up Node
  hosts: localhost
  become_user: "{{ username }}"
  tasks:
    #- name: install system node
      #become: True
      #become_user: root
      #package: name=nodejs10
               #state=latest

    - name: ensure the ~/src-hub directory is present
      file: path=/home/{{ username }}/src-hub
            state=directory

    - name: clone nvm
      git: repo=https://github.com/creationix/nvm.git
           dest=/home/{{ username }}/src-hub/nvm
           update=no

    - name: create symlink to nvm
      file: path=/home/{{ username }}/.nvm
            src=/home/{{ username }}/src-hub/nvm
            state=link

    - name: copy nvm.zsh to oh-my-zsh custom dir
      copy: src=nvm.zsh
            dest=/home/{{ username }}/.oh-my-zsh/custom/
            force=no
