---
- name: Install PostgreSQL and Extras
  hosts: localhost
  become: True
  become_user: root
  tasks:
    - name: install postgresql packages
      package: name={{ item }}
      with_items:
        - pgadmin3
        - postgresql
        - postgresql-contrib
        - postgresql-server

    - name: ensure database exists
      command: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/base

    - name: enable postgresql service
      service: name=postgresql
               enabled=yes
               state=started

    - name: enable password authentication on local
      lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
                  regexp='local\s+all\s+all\s+peer'
                  line='local  all  all    md5'
      notify: restart postgresql

    - name: enable password authentication on host
      lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
                  regexp='host\s+all\s+all\s+127.0.0.1/32\s+ident'
                  line='host  all  all  127.0.0.1/32  md5'
      notify: restart postgresql

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted
