- name: Enable RPM Fusion and Install a few things
  hosts: localhost
  become: True
  become_user: root
  tasks:
    - name: rpmfusion-free
      command: dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-28.noarch.rpm

    - name: set up rpmfusion nonfree repo
      command: dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-28.noarch.rpm

    - name: upgrade all packages
      package:
        name: "*"
        state: latest

    - name: install packages
      package: name={{ item }}
      with_items:
        - ffmpeg
        - ffmpeg-libs
        - gstreamer-ffmpeg

